force-app/main/default/objects/Log_Board_Settings__c/Log_Board_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Log Board Settings</label>
</CustomObject>

force-app/main/default/objects/Log_Board_Settings__c/fields/Log_Filter__c.field-meta.xml
<CustomField>
    <fullName>Log_Filter__c</fullName>
    <description>String value of WHERE clause for ApexLog SOQL query.</description>
    <inlineHelpText>String value of WHERE clause for ApexLog SOQL query.</inlineHelpText>
    <label>Log Filter</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/PostInstallClassTest.cls
@isTest
private class PostInstallClassTest {

    @isTest
    private static void installTest() {
        PostInstall postInstall = new PostInstall();
        Test.testInstall(postinstall, null);

        System.assert(Log_Board_Settings__c.getOrgDefaults() != null, 'Custom setting can not be null');
        System.assert(Log_Board_Settings__c.getOrgDefaults().Log_Filter__c != null, 'Log Filter setting can not be null');
    }
    
}